// Generated by Wrangler on Thu Sep 12 2024 06:40:18 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	MALACCA_USER: KVNamespace;
	MALACCA_CACHE: KVNamespace;
	MALACCA: AnalyticsEngineDataset;
}
