#:schema node_modules/wrangler/config-schema.json
name = "malacca"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
minify = true
logpush = false

# Bind an Analytics Engine dataset. Use Analytics Engine to write analytics within your Pages Function.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#analytics-engine-datasets
[[analytics_engine_datasets]]
binding = "MALACCA"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "MALACCA_USER"
id = "172f036565724816a51f04789deeecd0"

[[kv_namespaces]]
binding = "MALACCA_CACHE"
id = "8ef9a507dca94b21b4f64e40952c0dfd"

